#!/usr/bin/env python3
"""Deterministically validate artifacts generated by the handoff skill."""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

HANDOFF_HEADINGS = [
    "Outcome and current state",
    "Required reading and anchors",
    "Scope and owned components",
    "Non-goals",
    "Settled decisions and constraints",
    "Dependencies and prerequisites",
    "Implementation direction",
    "Acceptance criteria",
    "Validation",
    "Risks and assumptions",
    "Completion check",
    "Completion boundary and done condition",
    "Next-task handoff",
]
README_HEADINGS = [
    "Objective",
    "Verified starting state",
    "Ordered tasks",
    "Dependency graph",
    "Cross-task constraints",
    "Coverage map",
    "Final acceptance and validation",
]
PROGRESS_HEADINGS = [
    "Execution state",
    "Task checklist",
    "Completed outputs and validation",
    "Discoveries and deviations",
    "Blockers",
    "Next action",
]
TASK_PATTERN = re.compile(r"task-(\d{2})-[a-z0-9]+(?:-[a-z0-9]+)*\.md$")
AC_PATTERN = re.compile(r"\bAC(?:CEPTANCE CRITERION)?[- ]?(\d+)\b", re.IGNORECASE)


class Validation:
    def __init__(self) -> None:
        self.errors: list[str] = []
        self.warnings: list[str] = []

    def error(self, message: str) -> None:
        self.errors.append(message)

    def warn(self, message: str) -> None:
        self.warnings.append(message)


def read_text(path: Path, result: Validation) -> str:
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeError) as exc:
        result.error(f"cannot read {path}: {exc}")
        return ""
    if re.search(r"\{\{[^{}\n]+\}\}", text):
        result.error(f"{path}: unresolved template placeholder")
    return text


def check_headings(path: Path, text: str, required: list[str], result: Validation) -> None:
    headings = re.findall(r"^## (.+?)\s*$", text, re.MULTILINE)
    positions: list[int] = []
    for heading in required:
        count = headings.count(heading)
        if count != 1:
            result.error(f"{path}: expected exactly one '## {heading}' heading; found {count}")
        else:
            positions.append(headings.index(heading))
    if len(positions) == len(required) and positions != sorted(positions):
        result.error(f"{path}: required headings are out of order")


def validate_single(root: Path, result: Validation) -> None:
    handoff = root / "handoff.md"
    if not handoff.is_file():
        result.error(f"missing {handoff}")
        return
    check_headings(handoff, read_text(handoff, result), HANDOFF_HEADINGS, result)
    for opposite in (root / "README.md", root / "progress.md", root / "loop.sh"):
        if opposite.exists():
            result.error(f"single-session shape must not contain {opposite}")
    tasks = root / "tasks"
    if tasks.exists():
        result.error(f"single-session shape must not contain {tasks}")


def validate_readme_controls(path: Path, text: str, result: Validation) -> None:
    controls = {
        "progress update instruction": r"update `?progress\.md`?",
        "Conventional Commits instruction": r"Conventional Commits",
        "end-of-task report instruction": r"concise report",
        "generic completion marker": r"ralph-complete",
        "next-runnable-task routing": r"next runnable",
        "blocked no-runnable stop": r"Next task`?\s+(?:to\s+)?`?none`?.{0,160}blocked|blocked.{0,160}Next task`?\s+(?:to\s+)?`?none",
        "blocked-task retry prohibition": r"Never route back to a blocked task",
    }
    for label, pattern in controls.items():
        if not re.search(pattern, text, re.IGNORECASE):
            result.error(f"{path}: missing {label}")


def validate_loop_behavior(loop_path: Path, result: Validation) -> None:
    scenarios = [
        ("blocked", "blocked", "none", 3, "blocked with no runnable task", False),
        ("deadlock", "in progress", "none", 2, "No runnable task", False),
        ("no-progress", "in progress", "`task-01-one`", 4, "No progress.md update", False),
        ("route-around", "in progress", "`task-02-two`", 0, "task-02-two", True),
    ]
    with tempfile.TemporaryDirectory(prefix="handoff-loop-") as temp:
        temp_root = Path(temp)
        for name, status, next_task, expected_code, expected_text, completes in scenarios:
            case = temp_root / name
            tasks = case / "tasks"
            tasks.mkdir(parents=True)
            candidate = case / "loop.sh"
            shutil.copy2(loop_path, candidate)
            candidate.chmod(candidate.stat().st_mode | 0o111)
            (case / "README.md").write_text("# Ralph test prompt\n", encoding="utf-8")
            (case / "progress.md").write_text(
                "# Test progress\n\n"
                f"**Initiative status:** {status}\n"
                "**Current task:** none\n"
                f"**Next task:** {next_task}\n",
                encoding="utf-8",
            )
            for task_name in ("task-01-one", "task-02-two"):
                (tasks / f"{task_name}.md").write_text("# Test task\n", encoding="utf-8")
            agent = case / "fake-agent"
            completion_command = 'touch "$(dirname -- "$0")/ralph-complete"' if completes else ":"
            agent.write_text(f"#!/usr/bin/env bash\n{completion_command}\n", encoding="utf-8")
            agent.chmod(0o755)
            environment = os.environ.copy()
            environment.update({"RALPH_CMD": str(agent), "MAX_ITERATIONS": "2"})
            run = subprocess.run(
                [str(candidate)],
                capture_output=True,
                text=True,
                env=environment,
                check=False,
                timeout=10,
            )
            output = run.stdout + run.stderr
            if run.returncode != expected_code or expected_text not in output:
                result.error(
                    f"{loop_path}: {name} behavior failed "
                    f"(exit {run.returncode}, expected {expected_code}; output: {output.strip()!r})"
                )


def validate_ralph(root: Path, result: Validation) -> None:
    required_paths = [root / "README.md", root / "progress.md", root / "loop.sh", root / "tasks"]
    for path in required_paths:
        if not path.exists():
            result.error(f"missing {path}")
    if (root / "handoff.md").exists():
        result.error(f"Ralph shape must not contain {root / 'handoff.md'}")
    if any(not path.exists() for path in required_paths):
        return

    readme_path = root / "README.md"
    progress_path = root / "progress.md"
    loop_path = root / "loop.sh"
    readme = read_text(readme_path, result)
    progress = read_text(progress_path, result)
    loop = read_text(loop_path, result)
    check_headings(readme_path, readme, README_HEADINGS, result)
    check_headings(progress_path, progress, PROGRESS_HEADINGS, result)
    validate_readme_controls(readme_path, readme, result)

    for field in ("Initiative status", "Current task", "Next task", "Design authority"):
        if not re.search(rf"^\*\*{re.escape(field)}:\*\*\s*\S", progress, re.MULTILINE):
            result.error(f"{progress_path}: missing populated '{field}' field")

    task_files = sorted(path for path in (root / "tasks").glob("*.md") if path.is_file())
    if not task_files:
        result.error(f"{root / 'tasks'}: no task files")
    numbers: list[int] = []
    for task in task_files:
        match = TASK_PATTERN.fullmatch(task.name)
        if not match:
            result.error(f"{task}: name must match task-NN-kebab-slug.md")
            continue
        numbers.append(int(match.group(1)))
        task_text = read_text(task, result)
        check_headings(task, task_text, HANDOFF_HEADINGS, result)
        if not re.search(r"Do not retry a blocked task", task_text, re.IGNORECASE):
            result.error(f"{task}: missing blocked-task retry control")
        if task.name not in readme:
            result.error(f"{readme_path}: does not reference {task.name}")
        if task.stem not in progress:
            result.error(f"{progress_path}: does not reference {task.stem}")
    if numbers and numbers != list(range(1, len(numbers) + 1)):
        result.error(f"task numbers must be contiguous from 01; found {numbers}")

    design_path = root / "design.md"
    if design_path.is_file():
        design = read_text(design_path, result)
        design_acs = set(AC_PATTERN.findall(design))
        readme_acs = set(AC_PATTERN.findall(readme))
        missing_acs = sorted(design_acs - readme_acs, key=int)
        if missing_acs:
            result.error(
                f"{readme_path}: coverage map omits design AC IDs: {', '.join('AC' + n for n in missing_acs)}"
            )
        if not design_acs:
            result.warn(
                f"{design_path}: no explicit AC identifiers found; AC coverage could not be checked mechanically"
            )
    else:
        result.error(f"missing {design_path}")

    for token in (
        "RALPH_CMD",
        "MAX_ITERATIONS",
        "RALPH_SESSION_PREFIX",
        "ralph-complete",
        "README.md",
        "progress.md",
        "select_next_task",
        "BLOCKED_EXIT_CODE",
        "NO_PROGRESS_EXIT_CODE",
        "cksum",
    ):
        if token not in loop:
            result.error(f"{loop_path}: missing required token {token!r}")
    if not re.search(r'^RALPH_CMD=.* -ne(?: |")', loop, re.MULTILINE):
        result.error(f"{loop_path}: default RALPH_CMD must disable Pi extension discovery with -ne")
    if not re.search(r"session_name=.*\$\{task_name\}", loop):
        result.error(f"{loop_path}: session name must include the next task file stem")
    if not re.search(r'"\$\{ralph_command\[@\]\}"\s+-n\s+', loop):
        result.error(f"{loop_path}: Pi invocation must set a task-based session name with -n")
    if not loop_path.stat().st_mode & 0o111:
        result.error(f"{loop_path}: script is not executable")
    syntax = subprocess.run(["bash", "-n", str(loop_path)], capture_output=True, text=True, check=False)
    if syntax.returncode != 0:
        detail = syntax.stderr.strip() or "unknown syntax error"
        result.error(f"{loop_path}: bash -n failed: {detail}")
    else:
        validate_loop_behavior(loop_path, result)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("artifact_dir", type=Path, help=".agent-artifacts/<initiative-slug> directory")
    parser.add_argument("--shape", choices=("auto", "single", "ralph"), default="auto")
    args = parser.parse_args()
    root = args.artifact_dir.resolve()
    result = Validation()
    if not root.is_dir():
        result.error(f"artifact directory does not exist: {root}")
    else:
        shape = args.shape
        if shape == "auto":
            has_single = (root / "handoff.md").exists()
            has_ralph = any((root / name).exists() for name in ("README.md", "progress.md", "loop.sh", "tasks"))
            if has_single == has_ralph:
                result.error("cannot infer exactly one shape; use --shape after resolving missing or mixed artifacts")
            else:
                shape = "single" if has_single else "ralph"
        if not result.errors:
            (validate_single if shape == "single" else validate_ralph)(root, result)

    for warning in result.warnings:
        print(f"WARN: {warning}", file=sys.stderr)
    for error in result.errors:
        print(f"ERROR: {error}", file=sys.stderr)
    if result.errors:
        print(f"FAIL: {len(result.errors)} error(s), {len(result.warnings)} warning(s)", file=sys.stderr)
        return 1
    print(f"PASS: {root} ({args.shape}) with {len(result.warnings)} warning(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
